name: publish

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm publish --access publish
        working-directory: mongo-object-reader
        env: 
            NODE_AUTH_TOKEN:${{secrets.NPM_AUTH_TOKEN}}
